<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_ip extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Device_ip_model');
    } 

    /*
     * Listing of device_ip
     */
    function index()
    {
        $data['device_ip'] = $this->Device_ip_model->get_all_device_ip();
        
        $data['_view'] = 'device_ip/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new device_ip
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'device_id' => $this->input->post('device_id'),
				'ip_address' => $this->input->post('ip_address'),
            );
            
            $device_ip_id = $this->Device_ip_model->add_device_ip($params);
            redirect('device_ip/index');
        }
        else
        {            
            $data['_view'] = 'device_ip/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a device_ip
     */
    function edit($id)
    {   
        // check if the device_ip exists before trying to edit it
        $data['device_ip'] = $this->Device_ip_model->get_device_ip($id);
        
        if(isset($data['device_ip']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'device_id' => $this->input->post('device_id'),
					'ip_address' => $this->input->post('ip_address'),
                );

                $this->Device_ip_model->update_device_ip($id,$params);            
                redirect('device_ip/index');
            }
            else
            {
                $data['_view'] = 'device_ip/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The device_ip you are trying to edit does not exist.');
    } 

    /*
     * Deleting device_ip
     */
    function remove($id)
    {
        $device_ip = $this->Device_ip_model->get_device_ip($id);

        // check if the device_ip exists before trying to delete it
        if(isset($device_ip['id']))
        {
            $this->Device_ip_model->delete_device_ip($id);
            redirect('device_ip/index');
        }
        else
            show_error('The device_ip you are trying to delete does not exist.');
    }
    
}
