<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_door extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Device_door_model');
    } 

    /*
     * Listing of device_door
     */
    function index()
    {
        $data['device_door'] = $this->Device_door_model->get_all_device_door();
        
        $data['_view'] = 'device_door/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new device_door
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'device_id' => $this->input->post('device_id'),
				'door_id' => $this->input->post('door_id'),
            );
            
            $device_door_id = $this->Device_door_model->add_device_door($params);
            redirect('device_door/index');
        }
        else
        {
			$this->load->model('Device_master_model');
			$data['all_device_master'] = $this->Device_master_model->get_all_device_master();

			$this->load->model('Door_master_model');
			$data['all_door_master'] = $this->Door_master_model->get_all_door_master();
            
            $data['_view'] = 'device_door/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a device_door
     */
    function edit($id)
    {   
        // check if the device_door exists before trying to edit it
        $data['device_door'] = $this->Device_door_model->get_device_door($id);
        
        if(isset($data['device_door']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'device_id' => $this->input->post('device_id'),
					'door_id' => $this->input->post('door_id'),
                );

                $this->Device_door_model->update_device_door($id,$params);            
                redirect('device_door/index');
            }
            else
            {
				$this->load->model('Device_master_model');
				$data['all_device_master'] = $this->Device_master_model->get_all_device_master();

				$this->load->model('Door_master_model');
				$data['all_door_master'] = $this->Door_master_model->get_all_door_master();

                $data['_view'] = 'device_door/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The device_door you are trying to edit does not exist.');
    } 

    /*
     * Deleting device_door
     */
    function remove($id)
    {
        $device_door = $this->Device_door_model->get_device_door($id);

        // check if the device_door exists before trying to delete it
        if(isset($device_door['id']))
        {
            $this->Device_door_model->delete_device_door($id);
            redirect('device_door/index');
        }
        else
            show_error('The device_door you are trying to delete does not exist.');
    }
    
}
