<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Group_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Group_master_model');
    } 

    /*
     * Listing of group_master
     */
    function index()
    {
        $data['group_master'] = $this->Group_master_model->get_all_group_master();
        
        $data['_view'] = 'group_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new group_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'group_name' => $this->input->post('group_name'),
				'quota' => $this->input->post('quota'),
            );
            
            $group_master_id = $this->Group_master_model->add_group_master($params);
            redirect('group_master/index');
        }
        else
        {            
            $data['_view'] = 'group_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a group_master
     */
    function edit($id)
    {   
        // check if the group_master exists before trying to edit it
        $data['group_master'] = $this->Group_master_model->get_group_master($id);
        
        if(isset($data['group_master']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'group_name' => $this->input->post('group_name'),
					'quota' => $this->input->post('quota'),
                );

                $this->Group_master_model->update_group_master($id,$params);            
                redirect('group_master/index');
            }
            else
            {
                $data['_view'] = 'group_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The group_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting group_master
     */
    function remove($id)
    {
        $group_master = $this->Group_master_model->get_group_master($id);

        // check if the group_master exists before trying to delete it
        if(isset($group_master['id']))
        {
            $this->Group_master_model->delete_group_master($id);
            redirect('group_master/index');
        }
        else
            show_error('The group_master you are trying to delete does not exist.');
    }
    
}
