<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_master extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_master_model');
    } 

    /*
     * Listing of user_master
     */
    function index()
    {
        $data['user_master'] = $this->User_master_model->get_all_user_master();
        
        $data['_view'] = 'user_master/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_master
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'group_id' => $this->input->post('group_id'),
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
            );
            
            $user_master_id = $this->User_master_model->add_user_master($params);
            redirect('user_master/index');
        }
        else
        {
			$this->load->model('Group_master_model');
			$data['all_group_master'] = $this->Group_master_model->get_all_group_master();
            
            $data['_view'] = 'user_master/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_master
     */
    function edit($id)
    {   
        // check if the user_master exists before trying to edit it
        $data['user_master'] = $this->User_master_model->get_user_master($id);
        
        if(isset($data['user_master']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'group_id' => $this->input->post('group_id'),
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
                );

                $this->User_master_model->update_user_master($id,$params);            
                redirect('user_master/index');
            }
            else
            {
				$this->load->model('Group_master_model');
				$data['all_group_master'] = $this->Group_master_model->get_all_group_master();

                $data['_view'] = 'user_master/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_master you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_master
     */
    function remove($id)
    {
        $user_master = $this->User_master_model->get_user_master($id);

        // check if the user_master exists before trying to delete it
        if(isset($user_master['id']))
        {
            $this->User_master_model->delete_user_master($id);
            redirect('user_master/index');
        }
        else
            show_error('The user_master you are trying to delete does not exist.');
    }
    
}
