<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_door_access extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_door_access_model');
    } 

    /*
     * Listing of user_door_access
     */
    function index()
    {
        $data['user_door_access'] = $this->User_door_access_model->get_all_user_door_access();
        
        $data['_view'] = 'user_door_access/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_door_access
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'door_id' => $this->input->post('door_id'),
            );
            
            $user_door_access_id = $this->User_door_access_model->add_user_door_access($params);
            redirect('user_door_access/index');
        }
        else
        {
			$this->load->model('User_master_model');
			$data['all_user_master'] = $this->User_master_model->get_all_user_master();

			$this->load->model('Door_master_model');
			$data['all_door_master'] = $this->Door_master_model->get_all_door_master();
            
            $data['_view'] = 'user_door_access/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_door_access
     */
    function edit($id)
    {   
        // check if the user_door_access exists before trying to edit it
        $data['user_door_access'] = $this->User_door_access_model->get_user_door_access($id);
        
        if(isset($data['user_door_access']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'door_id' => $this->input->post('door_id'),
                );

                $this->User_door_access_model->update_user_door_access($id,$params);            
                redirect('user_door_access/index');
            }
            else
            {
				$this->load->model('User_master_model');
				$data['all_user_master'] = $this->User_master_model->get_all_user_master();

				$this->load->model('Door_master_model');
				$data['all_door_master'] = $this->Door_master_model->get_all_door_master();

                $data['_view'] = 'user_door_access/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_door_access you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_door_access
     */
    function remove($id)
    {
        $user_door_access = $this->User_door_access_model->get_user_door_access($id);

        // check if the user_door_access exists before trying to delete it
        if(isset($user_door_access['id']))
        {
            $this->User_door_access_model->delete_user_door_access($id);
            redirect('user_door_access/index');
        }
        else
            show_error('The user_door_access you are trying to delete does not exist.');
    }
    
}
