<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_billing_head extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in())
        {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
        $this->load->model('Up_billing_head_model');
    } 

    /*
     * Listing of up_billing_heads
     */
    function view_utility_billing_head()
    {
        $data = array(
            'title' => "Utility Service Provider"
        );
        $uplan_id = $this->uri->segment(3);
        $data['up_billing_heads'] = $this->Up_billing_head_model->get_all_up_billing_head($uplan_id);
        $data['_view'] = 'up_billing_head/index';
        $this->load->view('utility_provider/utility_provider_actions/view_utility_billing_head', $data);
    }

    /*
     * Adding a new up_billing_head
     */
    function add_utility_billing_head()
    {   
        $data = array(
            'title' => "Utility Service Provider"
        );
        $uplan_id = $this->uri->segment(3);
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_unit_value' => $this->input->post('utility_unit_value'),
				'utility_service_provider_id' => $this->input->post('usp_id'),
				'utility_plan_id' => $this->input->post('uplan_id'),
				// 'id' => $this->input->post('id'),
				'name' => $this->input->post('utility_bill_head_name'),
				'amount' => $this->input->post('utility_bill_head_amount'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
            );
            
            $up_billing_head_id = $this->Up_billing_head_model->add_up_billing_head($params);
            redirect('utility_billing_head/view'.'/'.$params['utility_plan_id'].'/'.$params['utility_service_provider_id']);
        }
        else
        {            
            $data['_view'] = 'up_billing_head/add';
            $this->load->view('utility_provider/utility_provider_actions/add_utility_billing_head', $data);
        }
    }  

    /*
     * Editing a up_billing_head
     */
    function edit_utility_billing_head($id = '')
    {
        $data = array(
            'title' => "Utility Service Provider"
        );
        if($id == ''){
            $id = $this->input->post('up_billing_head_id');
        }
        $uplan_id = $this->uri->segment(3);   
        // check if the up_billing_head exists before trying to edit it
        $data['up_billing_head'] = $this->Up_billing_head_model->get_up_billing_head($id);
        
        if(isset($data['up_billing_head']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_unit_value' => $this->input->post('utility_unit_value'),
					'utility_service_provider_id' => $this->input->post('usp_id'),
					'utility_plan_id' => $this->input->post('uplan_id'),
					// 'id' => $this->input->post('id'),
					'name' => $this->input->post('utility_bill_head_name'),
					'amount' => $this->input->post('utility_bill_head_amount'),
					// 'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
                );
                // echo $id;die;
                $this->Up_billing_head_model->update_up_billing_head($id,$params);           
                redirect('utility_billing_head/view'.'/'.$params['utility_plan_id'].'/'.$params['utility_service_provider_id']);
            }
            else
            {
                $data['_view'] = 'up_billing_head/edit';
                $this->load->view('utility_provider/utility_provider_actions/edit_utility_billing_head', $data);
            }
        }
        else
            show_error('The up_billing_head you are trying to edit does not exist.');
    } 

    /*
     * Deleting up_billing_head
     */
    function remove($id)
    {
        $id =  $this->uri->segment(3);
        $uplan_id = $this->uri->segment(4);
        $usp_id = $this->uri->segment(5);
        $up_billing_head = $this->Up_billing_head_model->get_up_billing_head($id);

        // check if the up_billing_head exists before trying to delete it
        if(isset($up_billing_head['id']))
        {
            $this->Up_billing_head_model->delete_up_billing_head($id);
            redirect('utility_billing_head/view'.'/'.$uplan_id.'/'.$usp_id);
        }
        else
            show_error('The up_billing_head you are trying to delete does not exist.');
    }
    
}
