<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_plan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in())
        {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
        $this->load->model('Utility_plan_model');
    } 

    /*
     * Listing of utility_plans
     */
    function view_plans()
    {
        $data = array(
            'title' => "Utility Service Provider"
        );
        $usp_id = $this->uri->segment(3);
        $data['utility_plans'] = $this->Utility_plan_model->get_all_utility_plan($usp_id);
        
        $data['_view'] = 'utility_plan/index';
        $this->load->view('utility_provider/utility_provider_actions/view_utility_plans', $data);
    }

    /*
     * Adding a new utility_plan
     */
    function add_plans()
    {   
        $data = array(
            'title' => "Utility Service Provider"
        );
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'utility_service_provider_id' => $this->input->post('usp_id'),
				'plan_name' => $this->input->post('utility_plan_name'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
            );
            
            $utility_plan_id = $this->Utility_plan_model->add_utility_plan($params);
            redirect('utility_plan/plans'.'/'.$params['utility_service_provider_id']);
        }
        else
        {            
            $data['_view'] = 'utility_plan/add';
            $this->load->view('utility_provider/utility_provider_actions/add_utility_plans', $data);
        }
    }  

    /*
     * Editing a utility_plan
     */
    function edit_plan($id = '')
    {
        if($id == ''){
            $id = $this->input->post('utility_plan_id');
        }
        $data = array(
            'title' => "Edit Utility Plan"
        );
        // check if the utility_plan exists before trying to edit it
        $data['utility_plan'] = $this->Utility_plan_model->get_utility_plan($id);
        
        if(isset($data['utility_plan']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'utility_service_provider_id' => $this->input->post('usp_id'),
					'plan_name' => $this->input->post('utility_plan_name'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
                );
                // echo $id;die;
                $this->Utility_plan_model->update_utility_plan($id,$params);            
                redirect('utility_plan/plans'.'/'.$params['utility_service_provider_id']);
            }
            else
            {
                $data['_view'] = 'utility_plan/edit';
                $this->load->view('utility_provider/utility_provider_actions/edit_utility_plans', $data);
            }
        }
        else
            show_error('The utility_plan you are trying to edit does not exist.');
    } 

    /*
     * Deleting utility_plan
     */
    function remove($id)
    {
        $id = $this->uri->segment(3);
        $usp_id = $this->uri->segment(4);
        $utility_plan = $this->Utility_plan_model->get_utility_plan($id);
        // check if the utility_plan exists before trying to delete it
        if(isset($utility_plan['utility_service_provider_id']))
        {
            $this->Utility_plan_model->delete_utility_plan($id);
            redirect('utility_plan/plans'.'/'.$usp_id);
        }
        else
            show_error('The utility_plan you are trying to delete does not exist.');
    }
    
}
