<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_provider_member extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in())
        {
            // redirect them to the login page
            redirect('auth/login', 'refresh');
        }
        $this->load->helper(['url', 'language']);
        $this->load->model('Utility_service_provider_member_model');
        $this->load->model('Utility_plan_model');
        $this->load->model('Member_model');
        $this->load->model('Society_model');
        $this->load->model('User_model');
        $this->load->model('Role_model');
        $this->load->model('Society_access_model');
        $this->load->model('Ion_auth_model');
        $this->load->library(['ion_auth', 'form_validation']);
        $this->form_validation->set_error_delimiters($this->config->item('error_start_delimiter', 'ion_auth'), $this->config->item('error_end_delimiter', 'ion_auth'));
        $this->lang->load('auth');
    } 

    /*
     * Listing of utility_service_provider_members
     */
    function manage_member()
    {
        $data = array(
            'title' => "Utility Service Provider"
        );
        $usp_id = $this->uri->segment(3);
        $usp_data = $data['utility_provider_members'] = $this->Utility_service_provider_member_model->get_all_utility_service_provider_member($usp_id);
        // $data['member'] = $member;
        $member_data_arr = array();
        $i = 0;
        foreach($usp_data as $abc)
        {
            $member_id = $abc['member_id'];
            $member_data = $this->Utility_service_provider_member_model->get_members_by_id_uspm($member_id);

            if($member_data){
                $member_data_arr[$i] = $member_data[0];
            }

        //echo "<pre>";print_r($data['member_data']);
        $i++;
        }
        $data['member_data'] = $member_data_arr;
        $data['_view'] = 'utility_provider_member/index';
        $this->load->view('utility_provider/members/manage_members', $data);
    }

    /*
     * Adding a new utility_service_provider_member
     */
    function add_member($society = '')
    {
        $data = array(
            'title' => "Utility Service Provider"
        );  
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $society_name = $this->input->post('society_name');
            $society_reg = $this->input->post('society_reg');
            $society_address = $this->input->post('society_address');

            $society = $this->Society_model->get_society_by_name_reg($society_name, $society_reg);

            if(!$society)
            {
                $params = array(
                        'name' => $this->input->post('society_name'),
                        'address' => $this->input->post('society_address'),
                        'registration_no' => $this->input->post('society_reg'),
                        'created_by_utility' => 1,
                    );

                    $society_id = $this->Society_model->add_society($params);

                    $params = array(
                        'society_id' => $society_id,
                        'wing' => $this->input->post('utility_member_wing'),
                        'flat_no' => $this->input->post('utility_member_flat'),
                        'name' => $this->input->post('utility_member_name'),
                        'phone' => $this->input->post('utility_member_phone'),
                        'email_id' => $this->input->post('utility_member_email'),
                    );

                    $member_id = $this->Member_model->add_member($params);

                    // $params = array(
                    //     'email' => $this->input->post('utility_member_email'),
                    //     'username' => $this->input->post('utility_member_email'),
                    //     'phone' => $this->input->post('utility_member_phone'),
                    //     'password' => md5('msociety123'),
                    // );

                    // $this->load->model('User_model');
                    // $username = $this->input->post('utility_member_email');
                    // // $society_id = $this->input->post('society_id');
                    // $user_member_id = $this->User_model->get_all_user_by_member_id($username);
                    // // print_r($user_member_id);die;
                    // if($user_member_id == NULL || $user_member_id == 0)
                    // {
                        $tables = $this->config->item('tables', 'ion_auth');
                        $identity_column = $this->config->item('identity', 'ion_auth');
                        $this->data['identity_column'] = $identity_column;
                        $email = strtolower($this->input->post('utility_member_email'));
                        $identity = ($identity_column === 'email') ? $email : $this->input->post('identity');
                        $password = 'msociety123';

                        $additional_data = [
                            'first_name' => $this->input->post('utility_member_name'),
                            'last_name' => '',
                            'company' => '',
                            'phone' => $this->input->post('utility_member_phone'),
                        ];
                        $group = array('10');
                        $user_id = $this->ion_auth->register($identity, $password, $email, $additional_data,$group);

                        $params = array(
                            'user_id' => $user_id,
                            'role_id' => 10,
                            'society_id' => $society_id,
                            'created_at' => $this->input->post('created_at'),
                            'updated_at' => $this->input->post('updated_at'),
                        );

                        $society_access_id = $this->Society_access_model->add_society_access($params);
                    // }
                    // else
                    // {
                    //     $data['_view'] = 'member/add';
                    //     $this->load->view('utility_provider/members/add_member', $data);
                    // }

                    $params = array(
                        'utility_service_provider_id' => $this->input->post('usp_id'),
                        'member_id' => $member_id,
                        'initial_outstanding' => $this->input->post('utility_member_outstanding'),
                        // 'utility_plan_id' => $this->input->post('utility_plan_id'),
                        'created_at' => $this->input->post('created_at'),
                        // 'updated_at' => $this->input->post('updated_at'),
                        'member_balance' => $this->input->post('member_balance'),
                    );

                    $utility_provider_member_id = $this->Utility_service_provider_member_model->add_utility_service_provider_member($params);
                    redirect('utility_provider_member/manage'.'/'.$params['utility_service_provider_id']);
            }
            else
            {
                $society_name = $this->input->post('society_name');
                $society_reg = $this->input->post('society_reg');
                $society_address = $this->input->post('society_address');

                $society = $this->Society_model->get_society_by_name_reg($society_name, $society_reg, $society_address);

                $society_id = $society[0]->id;
                $wing = $this->input->post('utility_member_wing');
                $flat_no = $this->input->post('utility_member_flat');
                $name = $this->input->post('utility_member_name');
                $phone = $this->input->post('utility_member_phone');
                $email = $this->input->post('utility_member_email');

                $member = $this->Member_model->get_member_by_details($society_id, $wing, $flat_no, $name, $phone, $email);
                
                if(!$member)
                {
                    $params = array(
                        'society_id' => $society_id = $society[0]->id,
                        'wing' => $this->input->post('utility_member_wing'),
                        'flat_no' => $this->input->post('utility_member_flat'),
                        'name' => $this->input->post('utility_member_name'),
                        'phone' => $this->input->post('utility_member_phone'),
                        'email_id' => $this->input->post('utility_member_email'),
                    );

                    $member_id = $this->Member_model->add_member($params);

                    // $params = array(
                    //     'email' => $this->input->post('utility_member_email'),
                    //     'username' => $this->input->post('utility_member_email'),
                    //     'phone' => $this->input->post('utility_member_phone'),
                    //     'password' => md5('msociety123'),
                    // );

                    // $this->load->model('User_model');
                    // $username = $this->input->post('utility_member_email');
                    // // $society_id = $this->input->post('society_id');
                    // $user_member_id = $this->User_model->get_all_user_by_member_id($username);
                    // // print_r($user_member_id);die;
                    // if($user_member_id == NULL || $user_member_id == 0)
                    // {
                    $tables = $this->config->item('tables', 'ion_auth');
                    $identity_column = $this->config->item('identity', 'ion_auth');
                    $this->data['identity_column'] = $identity_column;
                    $email = strtolower($this->input->post('utility_member_email'));
                    $identity = ($identity_column === 'email') ? $email : $this->input->post('identity');
                    $password = 'msociety123';

                    $additional_data = [
                        'first_name' => $this->input->post('utility_member_name'),
                        'last_name' => '',
                        'company' => '',
                        'phone' => $this->input->post('utility_member_phone'),
                    ];
                    $group = array('10');
                    $user_id = $this->ion_auth->register($identity, $password, $email, $additional_data,$group);
                        // $user_id = $this->User_model->add_user($params);

                    $params = array(
                        'user_id' => $user_id,
                        'role_id' => 10,
                        'society_id' => $society_id,
                        'created_at' => $this->input->post('created_at'),
                        'updated_at' => $this->input->post('updated_at'),
                    );

                    $society_access_id = $this->Society_access_model->add_society_access($params);
                    // }
                    // print_r($member_id);die;
                    $params = array(
                        'member_id' => $member_id,
                        // 'utility_plan_id' => $this->input->post('utility_plan_id'),
                        'utility_service_provider_id' => $this->input->post('usp_id'),
                        'created_at' => $this->input->post('created_at'),
                        'updated_at' => $this->input->post('updated_at'),
                        'member_balance' => $this->input->post('member_balance'),
                        'initial_outstanding' => $this->input->post('utility_member_outstanding'),
                    );
                    $utility_provider_member_id = $this->Utility_service_provider_member_model->add_utility_service_provider_member($params);
                    redirect('utility_provider_member/manage'.'/'.$params['utility_service_provider_id']);
                }
                else
                {
                     $params = array(
                        'member_id' => $member_id = $member[0]->id,
                        // 'utility_plan_id' => $this->input->post('utility_plan_id'),
                        'utility_service_provider_id' => $this->input->post('usp_id'),
                        'created_at' => $this->input->post('created_at'),
                        'updated_at' => $this->input->post('updated_at'),
                        'member_balance' => $this->input->post('member_balance'),
                        'initial_outstanding' => $this->input->post('utility_member_outstanding'),
                    );
                    $utility_provider_member_id = $this->Utility_service_provider_member_model->add_utility_service_provider_member($params);
                    redirect('utility_provider_member/manage'.'/'.$params['utility_service_provider_id']);
                }
            }  
        }
        else
        {            
            $data['_view'] = 'utility_provider_member/add';
            $this->load->view('utility_provider/members/add_member', $data);
        }
    }  

    /*
     * Editing a utility_service_provider_member
     */
    function edit_member($utility_service_provider_id)
    {   
        // check if the utility_service_provider_member exists before trying to edit it
        $data['utility_provider_member'] = $this->Utility_service_provider_member_model->get_utility_service_provider_member($utility_provider_id);
        
        if(isset($data['utility_provider_member']['utility_provider_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'utility_plan_id' => $this->input->post('utility_plan_id'),
					'id' => $this->input->post('id'),
					'member_id' => $this->input->post('member_id'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'member_balance' => $this->input->post('member_balance'),
					'initial_outstanding' => $this->input->post('initial_outstanding'),
                );

                $this->Utility_service_provider_member_model->update_utility_service_provider_member($utility_provider_id,$params);            
                redirect('utility_provider_member/manage');
            }
            else
            {
                $data['_view'] = 'utility_provider_member/edit';
                $this->load->view('utility_provider/members/edit_member', $data);
            }
        }
        else
            show_error('The utility_service_provider_member you are trying to edit does not exist.');
    }

    public function view_single_member($id) {
        $data = array(
            'title' => "Utility Service Provider"
        );
        // echo $id;die;
        $id = $this->uri->segment(3);
        $data['member'] = $this->Utility_service_provider_member_model->get_member_by_id_uspm($id);
        // echo "<pre>";print_r($data);die;
        $this->load->view('utility_provider/members/view_single_member', $data);
    }

    /*
     * Deleting utility_service_provider_member
     */
    function remove($utility_provider_id)
    {
        $utility_provider_member = $this->Utility_service_provider_member_model->get_utility_service_provider_member($utility_provider_id);

        // check if the utility_service_provider_member exists before trying to delete it
        if(isset($utility_provider_member['utility_service_provider_id']))
        {
            $this->Utility_service_provider_member_model->delete_utility_service_provider_member($utility_service_provider_id);
            redirect('utility_provider_member/manage_member');
        }
        else
            show_error('The utility_service_provider_member you are trying to delete does not exist.');
    }

    public function assign_plan() {
        $data = array(
            'title' => "Utility Service Provider"
        );

        if($this->input->post()){
            $post = $this->input->post('post_data');
            // print_r($post);die;
            $usp_id = $data['usp_id'] = $this->input->post('usp_id');
            foreach($post as $po => $v)
            {
                //echo "<pre>";var_dump($v);
                $params = array("utility_plan_id"=>$v['plan_name']);
                $umember_id = $v['utility_member_id'];
                // print_r($umember_id);die;
                $this->Utility_service_provider_member_model->update_utility_provider_member_plan($umember_id,$params);
            }
                /*$usp_id = $data['usp_id'] = $this->uri->segment(3);*//*echo "<pre>";print_r($usp_id);die;*/
                $usp_data = $data['utility_provider_member'] = $this->Utility_service_provider_member_model->get_all_utility_service_provider_member($usp_id);
                $i = 0;
                foreach($usp_data as $abc)
                {
                    $member_id = $abc['member_id'];
                    $member_data = $this->Utility_service_provider_member_model->get_members_by_id_uspm($member_id);

                    if($member_data){
                        $member_data_arr[$i] = $member_data[0];
                    }

            //echo "<pre>";print_r($data['member_data']);
                $i++;
                }
                $data['member_data'] = $member_data_arr;
                $data['utility_plans'] = $this->Utility_plan_model->get_all_utility_plan($usp_id);
                redirect('utility_provider_member/manage'.'/'.$usp_id);
                // echo "<pre>";print_r($$usp_data);die;
                       
            // }
            // die;
        }
        else
        {
            $usp_id = $data['usp_id'] = $this->uri->segment(3);
            $usp_data = $data['utility_provider_member'] = $this->Utility_service_provider_member_model->get_all_utility_service_provider_member($usp_id);
            $member_data_arr = array();
            $i = 0;
            foreach($usp_data as $abc)
            {
                $member_id = $abc['member_id'];
                $member_data = $this->Utility_service_provider_member_model->get_members_by_id_uspm($member_id);

                if($member_data){
                    $member_data_arr[$i] = $member_data[0];
                }

            //echo "<pre>";print_r($data['member_data']);
            $i++;
            }
             $data['member_data'] = $member_data_arr;
            $data['utility_plans'] = $this->Utility_plan_model->get_all_utility_plan($usp_id);
            // echo "<pre>";print_r($data['utility_plans']);die;
        }
        
        $this->load->view('utility_provider/utility_provider_actions/assign_plans', $data);
    }
    
}
