<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_ip_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get device_ip by id
     */
    function get_device_ip($id)
    {
        return $this->db->get_where('device_ip',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all device_ip
     */
    function get_all_device_ip()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('device_ip')->result_array();
    }
        
    /*
     * function to add new device_ip
     */
    function add_device_ip($params)
    {
        $this->db->insert('device_ip',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update device_ip
     */
    function update_device_ip($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('device_ip',$params);
    }
    
    /*
     * function to delete device_ip
     */
    function delete_device_ip($id)
    {
        return $this->db->delete('device_ip',array('id'=>$id));
    }
}
