<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Group_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get group_master by id
     */
    function get_group_master($id)
    {
        return $this->db->get_where('group_master',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all group_master
     */
    function get_all_group_master()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('group_master')->result_array();
    }
        
    /*
     * function to add new group_master
     */
    function add_group_master($params)
    {
        $this->db->insert('group_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update group_master
     */
    function update_group_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('group_master',$params);
    }
    
    /*
     * function to delete group_master
     */
    function delete_group_master($id)
    {
        return $this->db->delete('group_master',array('id'=>$id));
    }
}
