<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_master by id
     */
    function get_user_master($id)
    {
        return $this->db->get_where('user_master',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all user_master
     */
    function get_all_user_master()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('user_master')->result_array();
    }
        
    /*
     * function to add new user_master
     */
    function add_user_master($params)
    {
        $this->db->insert('user_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_master
     */
    function update_user_master($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_master',$params);
    }
    
    /*
     * function to delete user_master
     */
    function delete_user_master($id)
    {
        return $this->db->delete('user_master',array('id'=>$id));
    }
}
