<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_door_access_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_door_access by id
     */
    function get_user_door_access($id)
    {
        return $this->db->get_where('user_door_access',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all user_door_access
     */
    function get_all_user_door_access()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('user_door_access')->result_array();
    }
        
    /*
     * function to add new user_door_access
     */
    function add_user_door_access($params)
    {
        $this->db->insert('user_door_access',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_door_access
     */
    function update_user_door_access($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_door_access',$params);
    }
    
    /*
     * function to delete user_door_access
     */
    function delete_user_door_access($id)
    {
        return $this->db->delete('user_door_access',array('id'=>$id));
    }
	
	function get_device_id_by_door_id($door_id,$user_id){
		$res = $this->db->get_where('device_door',array('door_id'=>$door_id));
		if($res->num_rows() > 0){
			return $res->result_array()[0]['device_id'];
		} else {
			return false;
		}
	}
	
	function get_transfer_status_by_device_id($device_id){
		$res = $this->db->where(array('device_id'=>$device_id,'status'=>'ON','transferred'=>0))->order_by('id DESC')->limit('1')->get('request');
		if($res->num_rows() > 0){
			return $res->result_array()[0];
		} else {
			return false;
		}
	}
}
