<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Activity_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get activity_log by id
     */
    function get_activity_log($id)
    {
        return $this->db->get_where('activity_logs',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all activity_logs
     */
    function get_all_activity_logs()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('activity_logs')->result_array();
    }
        
    /*
     * function to add new activity_log
     */
    function add_activity_log($params)
    {
        $this->db->insert('activity_logs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update activity_log
     */
    function update_activity_log($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('activity_logs',$params);
    }
    
    /*
     * function to delete activity_log
     */
    function delete_activity_log($id)
    {
        return $this->db->delete('activity_logs',array('id'=>$id));
    }
}
