<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bank_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bank by id
     */
    function get_bank($id)
    {
        return $this->db->get_where('banks',array('id'=>$id))->row_array();
    }

    function get_bank_by_bank_society($society_id, $bank_name)
    {
        $this->db->where('society_id', $society_id);
        $this->db->where('bank_name', $bank_name);
        $bank = $this->db->get('banks');
        return $bank->result();
    }
        
    /*
     * Get all banks
     */
    function get_all_banks()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('banks')->result_array();
    }

    function get_all_bank($society_id)
    {
        $this->db->where('society_id', $society_id);
        // $this->db->order_by('id', 'desc');
        return $this->db->get('banks')->result_array();
    }

    function get_all_default_bank($id, $society_id)
    {
        $this->db->where('society_id', $society_id);
        $this->db->where('id !=', $id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('banks')->result_array();
    }

    function get_default_bank($society_id)
    {
        return $this->db->get_where('banks',array('society_id'=>$society_id, 'is_default'=>1))->row_array();
        // $this->db->where('society_id', $society_id);
        // $this->db->where('is_default', 1);
        // $this->db->order_by('id', 'desc');
        // return $this->db->get('banks')->result_array();
    }
        
    /*
     * function to add new bank
     */
    function add_bank($params)
    {
        $this->db->insert('banks',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bank
     */
    function update_bank($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('banks',$params);
    }
    
    /*
     * function to delete bank
     */
    function delete_bank($id)
    {
        $this->db->delete('bank_transactions', array('bank_id'=>$id));
        return $this->db->delete('banks',array('id'=>$id));
    }


    // function get_accounting_bank($society_id,$bank_id)
    // {        
    //     $this->db->where(array('ledger_id !='=>0,'bank_id'=>$bank_id,'society_id'=> $society_id))  ; 
    //     return $this->db->get('sc_bank_acc_details')->row();
    // }

    // function add_acc_bank($params)
    // {
    //     $this->db->insert('sc_bank_acc_details',$params);
    //     return $this->db->insert_id();
    // }

    // function update_acc_bank($id,$params)
    // {
    //     $this->db->where('bank_id',$id);
    //     return $this->db->update('sc_bank_acc_details',$params);
    // }
}
