<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Billing_head_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get billing_head by id
     */
    function get_billing_head($id)
    {
        return $this->db->get_where('billing_heads',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all billing_heads
     */
    function get_all_billing_heads($flat_type_id)
    {
        $this->db->where('flat_type_id', $flat_type_id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('billing_heads')->result_array();
    }

    function get_bill_heads_by_society($society_id)
    {
        // $this->db->select('name');
        $this->db->select('name');
        $this->db->distinct();
        $this->db->where('society_id', $society_id);
        //$this->db->order_by('id', 'desc');
        return $this->db->get('billing_heads')->result_array();
    }

    function get_bill_heads_by_society_id($society_id)
    {
        // $this->db->select('name');
        $this->db->select('name, amount');
        // $this->db->distinct();
        $this->db->where('society_id', $society_id);
        //$this->db->order_by('id', 'desc');
        return $this->db->get('billing_heads')->result_array();
    }

    function get_bill_heads_for_society($society_id)
    {
        // $this->db->select('name');
        $this->db->select('name,is_unit_value,amount');
        // $this->db->distinct();
        $this->db->where('society_id', $society_id);
        //$this->db->order_by('id', 'desc');
        return $this->db->get('billing_heads')->result_array();
    }

    function get_bill_heads_by_member_society($society_id)
    {
        // $this->db->select('name');
        // $this->db->select('name, amount');
        // $this->db->distinct();
        $this->db->where('society_id', $society_id);
        //$this->db->order_by('id', 'desc');
        return $this->db->get('billing_heads')->result_array();
    }

    function get_last_bill_no($society_id){
        $this->db->select('bill_no');
        $this->db->where('society_id',$society_id);
        $this->db->limit(1);
        $this->db->order_by('id DESC');
        $query = $this->db->get('bill_details');
        
        return ($query->num_rows() > 0)? $query->result_array()[0]['bill_no'] : 0;
    }
        
    /*
     * function to add new billing_head
     */
    function add_billing_head($params)
    {
        $this->db->insert('billing_heads',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update billing_head
     */
    function update_billing_head($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('billing_heads',$params);
    }
    
    /*
     * function to delete billing_head
     */
    function delete_billing_head($id)
    {
        return $this->db->delete('billing_heads',array('id'=>$id));
    }


    //   check flat type bill head details by mutiple condition 

    function flat_type_bill($bill_name,$flat_type_id,$society_id){
        $this->db->where('name',$bill_name);
        $this->db->where('flat_type_id',$flat_type_id);
        $this->db->where('society_id',$society_id);
        $query = $this->db->get('billing_heads');       
        if($query->num_rows() > 0){
            return 1;
        }else{
            return 0;
        }
        
    }
    ///get group id- sachhidanad 31-12-2021/////
    function get_bill_group_id($name){
        $this->db->select('ref_group_id');
        $this->db->where(array('bill_head_name'=> $name)); 
        $bill_id= $this->db->get('sc_bill_heads')->row(); 

        return $bill_id->ref_group_id;
    }


    //get all bill head master list
    function get_all_bill_head_master()
    {       
        $this->db->order_by('bill_head_id', 'desc');
        return $this->db->get('sc_bill_heads')->result_array();
    }

    /*
     * Get billing_head by id
     */
    function get_bill_head($id)
    {
        return $this->db->get_where('sc_bill_heads',array('bill_head_id'=>$id))->row_array();
    }

    function get_bill_head_category($cat_id=0)
    {   if($cat_id==0){
            $this->db->order_by('bill_head_category_name', 'asc');
            return $this->db->get('sc_bill_head_category')->result_array();
        }else{
            $this->db->select('c1.bill_head_category_id,c1.bill_head_category_name,c2.bill_head_category_id as parent_id,c2.bill_head_category_name as parent_name');
            $this->db->from('sc_bill_head_category c1');
            $this->db->join('sc_bill_head_category c2', 'c1.parent_id = c2.bill_head_category_id', 'left');
            $this->db->where(array('c1.bill_head_category_id'=> $cat_id));
            $query = $this->db->get()->row();
            return $query;
            
   
        }        
    }


     /*
     * function to add  edit  bill head
     */
    function add_edit_bill_head_master($id=0,$params)
    {   
        $result=0;
        if($id==0){
            $this->db->insert('sc_bill_heads',$params);
            $result=1;
           // return $this->db->insert_id();
        }else{
            $this->db->where('bill_head_id',$id);
            $this->db->update('sc_bill_heads',$params);
            $result=2;
        }
        return $result;
    }

    /*
     * Get master billing head by id
     */
    function get_master_billing_head($id)
    {
        return $this->db->get_where('sc_bill_heads',array('bill_head_id'=>$id))->row_array();
    }

     /*
     * function to check existing bill head- sachhidanand 
     */
    function exist_billing_head($bill_head_name)
    {
        $this->db->like('bill_head_name', $bill_head_name);
        // $this->db->where('bill_head_name', $bill_head_name);       
        $bill=$this->db->get('sc_bill_heads')->row_array();
        
        if(!empty($bill)){
            return 1;
        }else{
            return 0;
        }
    }
    //bill head exit in society
    function exist_billing_head_in_society($bill_head_name)
    {
        $this->db->like('name', $bill_head_name);       
        $bill=$this->db->get('billing_heads')->row();
        return $bill;       
        
    }

    function delete_master_billing_head($id)
    {
        return $this->db->delete('sc_bill_heads',array('bill_head_id'=>$id));
    }


    function get_master_billing_head_details_by_name($bill_head_name)
    {
        $this->db->like('bill_head_name', $bill_head_name);               
        $bill=$this->db->get('sc_bill_heads')->row_array();        
        if(!empty($bill)){
            return $bill;
        }else{
            return false;
        }
    }


    function get_bill_details_by_name_flat_type_and_society_id($bill_name,$flat_type_id,$society_id){
        $this->db->where('name',$bill_name);
        $this->db->where('flat_type_id',$flat_type_id);
        $this->db->where('society_id',$society_id);
        return  $this->db->get('billing_heads')->row_array();
    }

    //check bill head in master table
    function check_billing_head_in_master($bill_head_name)
    {
        $this->db->where('bill_head_name', $bill_head_name);       
        $bill=$this->db->get('sc_bill_heads')->row_array();        
        if(!empty($bill)){
            return $bill;
        }else{
            return false;
        }
    }
   
    

}
