<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class CityState_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get expense by id
     */
    function get_state($id)
    {
        return $this->db->get_where('state',array('id'=>$id,'is_deleted'=>0))->row_array();
    }

    function get_city($id)
    {
        return $this->db->get_where('city',array('id'=>$id,'is_deleted'=>0))->row_array();
    }
        
    /*
     * Get all State
     */
    function get_all_state()
    {
        $this->db->where('is_deleted', 0);
        $this->db->order_by('name');
        return $this->db->get('state')->result_array();
    }

    function get_all_city()
    {
        $this->db->select('city.id as city_id, state.id, state.name,city.city_name');
        $this->db->where('city.is_deleted', 0);
        $this->db->join('state', 'state.id = city.state_id');
        $this->db->order_by('city.city_name', 'asc');
        return $this->db->get('city')->result_array();
    }

    function get_all_city_by_state($state_id)
    {
        $this->db->where('state_id', $state_id);
        $this->db->order_by('city.city_name', 'asc');
        return $this->db->get('city')->result_array();
    }
        
    /*
     * function to add new expense
     */
    function add_state($params)
    {
        $this->db->insert('state',$params);
        return $this->db->insert_id();
    }

    function add_city($params)
    {
        // print_r($params);die;
        $this->db->insert('city',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update expense
     */
    function update_state($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('state',$params);
    }

    function update_city($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('city',$params);
    }
    
    /*
     * function to delete expense
     */
    function delete_state($id)
    {
        return $this->db->delete('state',array('id'=>$id));
    }

    function delete_city($id)
    {
        return $this->db->delete('city',array('id'=>$id));
    }

    function get_city_state($state_id,$city_name)
    {
        return $this->db->get_where('city',array('state_id'=>$state_id,"city_name"=>$city_name,'is_deleted'=>0))->row_array();
    }

    function check_state_exit_society($state_id)
    {
        return $this->db->get_where('societies',array('state_id'=>$state_id))->result_array();
    }
    function check_city_exit_society($city_id)
    {
        return $this->db->get_where('societies',array('city_id'=>$city_id))->result_array();
    }
}
