<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Flat_sub_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get flat_sub_type by id
     */
    function get_flat_sub_type($id)
    {
        return $this->db->get_where('flat_sub_types',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all flat_sub_types
     */
    function get_all_flat_sub_types()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('flat_sub_types')->result_array();
    }
        
    /*
     * function to add new flat_sub_type
     */
    function add_flat_sub_type($params)
    {
        $this->db->insert('flat_sub_types',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update flat_sub_type
     */
    function update_flat_sub_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('flat_sub_types',$params);
    }
    
    /*
     * function to delete flat_sub_type
     */
    function delete_flat_sub_type($id)
    {
        return $this->db->delete('flat_sub_types',array('id'=>$id));
    }
}
