<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Flat_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get flat_type by id
     */
    function get_flat_type($id)
    {
        return $this->db->get_where('flat_types',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all flat_types
     */
    function get_all_flat_type($society_id)
    {
        $this->db->where('society_id', $society_id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('flat_types')->result_array();
    }

    function get_all_flat_types()
    {
        // $this->db->where('society_id', $society_id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('flat_types')->result_array();
    }
        
    /*
     * function to add new flat_type
     */
    function add_flat_type($params)
    {
        $this->db->insert('flat_types',$params);
        return $this->db->insert_id();
    }

    
    /*
     * function to update flat_type
     */
    function update_flat_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('flat_types',$params);
    }
    
    /*
     * function to delete flat_type
     */
    function delete_flat_type($id)
    {
        return $this->db->delete('flat_types',array('id'=>$id));
    }
    /* get single flat type by name -sachhidanand 
    **/
    function get_single_flat_types_by_name($flat_type_name,$society_id)
    {
        $this->db->where('society_id', $society_id);
        $this->db->where('name', $flat_type_name);       
        return $this->db->get('flat_types')->row();
    }

   
    
        
}
