<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Parking_charge_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get parking_charge by id
     */
    function get_parking_charge($id)
    {
        return $this->db->get_where('parking_charges',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all parking_charges
     */
    function get_all_parking_charges()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('parking_charges')->result_array();
    }

    function get_all_parking_charge($society_id)
    {
        $this->db->where('society_id', $society_id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('parking_charges')->result_array();
    }
        
    /*
     * function to add new parking_charge
     */
    function add_parking_charge($params)
    {
        $this->db->insert('parking_charges',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update parking_charge
     */
    function update_parking_charge($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('parking_charges',$params);
    }
    
    /*
     * function to delete parking_charge
     */
    function delete_parking_charge($id)
    {
        return $this->db->delete('parking_charges',array('id'=>$id));
    }
    
}
