<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get role by id
     */
    function get_role($id)
    {
        return $this->db->get_where('roles',array('id'=>$id))->row_array();
    }

    /*
     * Get role by name -13-02-2022 sachhidanand
     */
    function get_role_by_name($role_name)
    {
        return $this->db->get_where('roles',array('name'=>$role_name))->row_array();
    }
        
    /*
     * Get all roles
     */
    function get_all_roles()
    {
        $this->db->order_by('name', 'asc'); //display role by name-sachhidanand
        return $this->db->get('roles')->result_array();
    }

    function get_main_roles($role_id=null)
    {
        $this->db->where_in('id',$role_id);
        // $this->db->order_by('name', 'asc'); //display role by name-sachhidanand
        return $this->db->get('roles')->result_array();
    }
        
    /*
     * function to add new role
     */
    function add_role($params)
    {
        $this->db->insert('roles',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update role
     */
    function update_role($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('roles',$params);
    }
    
    /*
     * function to delete role
     */
    function delete_role($id)
    {
        return $this->db->delete('roles',array('id'=>$id));
    }
}
