<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Society_service_provider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get society_service_provider by 
     */
    function get_society_service_provider($)
    {
        return $this->db->get_where('society_service_providers',array(''=>$))->row_array();
    }
        
    /*
     * Get all society_service_providers
     */
    function get_all_society_service_providers()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('society_service_providers')->result_array();
    }
        
    /*
     * function to add new society_service_provider
     */
    function add_society_service_provider($params)
    {
        $this->db->insert('society_service_providers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update society_service_provider
     */
    function update_society_service_provider($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('society_service_providers',$params);
    }
    
    /*
     * function to delete society_service_provider
     */
    function delete_society_service_provider($)
    {
        return $this->db->delete('society_service_providers',array(''=>$));
    }
}
