<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Society_enrollment_request_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get society_enrollment_request by id
     */
    function get_society_enrollment_request($id)
    {
        return $this->db->get_where('society_enrollment_requests',array('id'=>$id))->row_array();
    }

    function get_total_enrollments(){
        // $this->db->where('account_status', $i);
        $num_rows = $this->db->count_all_results('society_enrollment_requests');
        return $num_rows;
    }

    function get_today_enrollments(){
        $today = date('Y-m-d');
        $this->db->where('created_at', $today);
        $num_rows = $this->db->count_all_results('society_enrollment_requests');
        return $num_rows;
    }
        
    /*
     * Get all society_enrollment_requests
     */
    function get_all_society_enrollment_requests()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('society_enrollment_requests')->result_array();
    }
        
    /*
     * function to add new society_enrollment_request
     */
    function add_society_enrollment_request($params)
    {
        $this->db->insert('society_enrollment_requests',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update society_enrollment_request
     */
    function update_society_enrollment_request($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('society_enrollment_requests',$params);
    }
    
    /*
     * function to delete society_enrollment_request
     */
    function delete_society_enrollment_request($id)
    {
        return $this->db->delete('society_enrollment_requests',array('id'=>$id));
    }
}
