<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tax_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get expense_category by id
     */
    function get_services_category($id)
    {
        return $this->db->get_where('service_master',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all expense_categories
     */
    function get_all_services_categories()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('service_master')->result_array();
    }
        
    /*
     * function to add new expense_category
     */
    function add_tax($params,$params2)
    {

         print_r($params);
     print_r($params2);
     die();
     
        $this->db->insert('service_master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update expense_category
     */
    function update_services_category($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('service_master',$params);
    }
    
    /*
     * function to delete expense_category
     */
    function delete_expense_category($id)
    {
        return $this->db->delete('service_master',array('id'=>$id));
    }
}
