<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Up_bill_detail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get up_bill_detail by 
     */
    function get_up_bill_detail($)
    {
        return $this->db->get_where('up_bill_details',array(''=>$))->row_array();
    }
        
    /*
     * Get all up_bill_details
     */
    function get_all_up_bill_details()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('up_bill_details')->result_array();
    }
        
    /*
     * function to add new up_bill_detail
     */
    function add_up_bill_detail($params)
    {
        $this->db->insert('up_bill_details',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update up_bill_detail
     */
    function update_up_bill_detail($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('up_bill_details',$params);
    }
    
    /*
     * function to delete up_bill_detail
     */
    function delete_up_bill_detail($)
    {
        return $this->db->delete('up_bill_details',array(''=>$));
    }
}
