<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Up_billing_head_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get up_billing_head by 
     */
    function get_up_billing_head($id)
    {
        return $this->db->get_where('up_billing_heads',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all up_billing_heads
     */
    function get_all_up_billing_heads()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('up_billing_heads')->result_array();
    }

    function get_all_up_billing_head($uplan_id)
    {
        $this->db->where('utility_plan_id', $uplan_id);
        $this->db->order_by('id', 'desc');
        return $this->db->get('up_billing_heads')->result_array();
    }
        
    /*
     * function to add new up_billing_head
     */
    function add_up_billing_head($params)
    {
        $this->db->insert('up_billing_heads',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update up_billing_head
     */
    function update_up_billing_head($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('up_billing_heads',$params);
    }
    
    /*
     * function to delete up_billing_head
     */
    function delete_up_billing_head($id)
    {
        return $this->db->delete('up_billing_heads',array('id'=>$id));
    }
}
