<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Up_payment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get up_payment by id
     */
    function get_up_payment($id)
    {
        return $this->db->get_where('up_payments',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all up_payments
     */
    function get_all_up_payments()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('up_payments')->result_array();
    }
        
    /*
     * function to add new up_payment
     */
    function add_up_payment($params)
    {
        $this->db->insert('up_payments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update up_payment
     */
    function update_up_payment($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('up_payments',$params);
    }
    
    /*
     * function to delete up_payment
     */
    function delete_up_payment($id)
    {
        return $this->db->delete('up_payments',array('id'=>$id));
    }
}
