<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_service_provider_member_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get utility_service_provider_member by utility_service_provider_id
     */
    function get_utility_service_provider_member($utility_service_provider_id)
    {
        return $this->db->get_where('utility_service_provider_members',array('utility_service_provider_id'=>$utility_service_provider_id))->row_array();
    }

    function get_members_by_id_uspm($member_id)
    {
        $this->db->where('m.id', $member_id);
        $this->db->join('utility_service_provider_members uspm', 'm.id = uspm.member_id');
        $this->db->order_by('m.id', 'desc');
        return $this->db->get('members m')->result_array();
    }

    function get_member_by_id_uspm($id)
    {
        // return $this->db->join('utility_service_provider_members uspm', 'm.id = uspm.member_id')->get_where('members m',array('m.id'=>$id))->result();
        $this->db->where('uspm.id', $id);
        $this->db->join('utility_service_provider_members uspm', 'm.id = uspm.member_id');
        return $this->db->get('members m')->result();
    }
        
    /*
     * Get all utility_service_provider_members
     */
    function get_all_utility_service_provider_members()
    {
        $this->db->order_by('utility_service_provider_id', 'desc');
        return $this->db->get('utility_service_provider_members')->result_array();
    }

    function get_all_utility_service_provider_member($usp_id)
    {
        $this->db->where('utility_service_provider_id', $usp_id);
        $this->db->order_by('utility_service_provider_id', 'desc');
        return $this->db->get('utility_service_provider_members')->result_array();
    }
        
    /*
     * function to add new utility_service_provider_member
     */
    function add_utility_service_provider_member($params)
    {
        $this->db->insert('utility_service_provider_members',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update utility_service_provider_member
     */
    function update_utility_service_provider_member($utility_service_provider_id,$params)
    {
        $this->db->where('utility_service_provider_id',$utility_service_provider_id);
        return $this->db->update('utility_service_provider_members',$params);
    }

    function update_utility_provider_member_plan($umember_id,$params)
    {
        $this->db->where('id',$umember_id);
        return $this->db->update('utility_service_provider_members',$params);
    }
    
    /*
     * function to delete utility_service_provider_member
     */
    function delete_utility_service_provider_member($utility_service_provider_id)
    {
        return $this->db->delete('utility_service_provider_members',array('utility_service_provider_id'=>$utility_service_provider_id));
    }

    function delete_utility_member_by_member($id)
    {
        return $this->db->delete('utility_service_provider_members',array('member_id'=>$id));
    }
}
