<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_service_provider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get utility_service_provider by id
     */
    function get_utility_service_provider($id)
    {
        return $this->db->get_where('utility_service_providers',array('id'=>$id))->row_array();
    }

    function get_utility_provider_details($id)
    {
        return $this->db->get_where('utility_service_providers',array('id'=>$id))->result();
    }
        
    /*
     * Get all utility_service_providers
     */
    function get_all_utility_service_providers()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('utility_service_providers')->result_array();
    }
        
    /*
     * function to add new utility_service_provider
     */
    function add_utility_service_provider($params)
    {
        $this->db->insert('utility_service_providers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update utility_service_provider
     */
    function update_utility_service_provider($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('utility_service_providers',$params);
    }
    
    /*
     * function to delete utility_service_provider
     */
    function delete_utility_service_provider($id)
    {
        return $this->db->delete('utility_service_providers',array('id'=>$id));
    }
}
