<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Utility_bill_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get utility_bill by member_id
     */
    function get_utility_bill($member_id)
    {
        return $this->db->get_where('utility_bills',array('member_id'=>$member_id))->row_array();
    }
        
    /*
     * Get all utility_bills
     */
    function get_all_utility_bills()
    {
        $this->db->order_by('member_id', 'desc');
        return $this->db->get('utility_bills')->result_array();
    }
        
    /*
     * function to add new utility_bill
     */
    function add_utility_bill($params)
    {
        $this->db->insert('utility_bills',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update utility_bill
     */
    function update_utility_bill($member_id,$params)
    {
        $this->db->where('member_id',$member_id);
        return $this->db->update('utility_bills',$params);
    }
    
    /*
     * function to delete utility_bill
     */
    function delete_utility_bill($member_id)
    {
        return $this->db->delete('utility_bills',array('member_id'=>$member_id));
    }
}
